openapi: '3.0.2'
info:
  title: Starter Project
  version: '1.0'

servers:
  - url: http://yasmin.framework/
    description: Development Custom Vhost
  - url: http://localhost:8091/
    description: Development

tags:
  - name: Kontak
    description: Manajemen data kontak
  - name: Grup
    description: Manajemen data grup
  - name: Test
    description: Manajemen data Test

paths:
  /kontak:
    $ref: './paths/kontak/kontak.yaml'
  /kontak/{idKontak}:
    $ref: './paths/kontak/kontak-{idKontak}.yaml'

  /grup:
    get:
      summary: Mengambil data grup
      tags: [Grup]
      responses:
        '200':
          description: Semua data grup