openapi: '3.0.2'
info:
  title: Starter Project
  version: '1.0'

servers:
  - url: http://localhost:8091/
    description: Development

tags:
  - name: Kontak
    description: Manajemen data kontak
  - name: Grup
    description: Manajemen data grup

paths:
  /kontak:
    get:
      summary: Mengambil data kontak
      tags: [Kontak]
      responses:
        '200':
          description: Semua data kontak

  /grup:
    get:
      summary: Mengambil data grup
      tags: [Grup]
      responses:
        '200':
          description: Semua data grup