openapi: 3.0.0

info:
  title: Yasmin Framework Playground
  description: Digunakan untuk melakukan testing fitur dan performa Yasmin Framework
  version: 1.0.0

servers:
  - url: http://localhost:8091/
    description: Default
  - url: http://localhost:8091/mysql/
    description: MySQL Driver
  - url: http://localhost:8091/sqlsrv/
    description: SQLSrv Driver
  - url: http://yasmin.framework/
    description: Local Vhost

tags:
  - name: Kontak
    description: Mengelola data kontak
  - name: Grup
    description: Mengelola data Grup
  - name: Produk
    description: Mengelola data Produk
  - name: Transaksi
    description: Mengelola data Transaksi
  - name: Poliklinik
    description: Mengelola data Poliklinik

paths:
  # /kontak:
  #   $ref: './paths/Kontak/Kontak.yaml'
  # /kontak/{idKontak}:
  #   $ref: './paths/Kontak/Kontak-{idKontak}.yaml'

  /grup:
    $ref: './paths/Grup/Grup.yaml'
  /grup/{idGrup} :
    $ref: './paths/Grup/Grup-{idGrup}.yaml'

  /produk:
    $ref: './paths/Produk/Produk.yaml'
  /produk/{idProduk}:
    $ref: './paths/Produk/Produk-{idProduk}.yaml'

  /poliklinik:
    $ref: './paths/Poliklinik/Poliklinik.yaml'
  /poliklinik/{idPoliklinik}:
    $ref: './paths/Poliklinik/Poliklinik-{idPoliklinik}.yaml'

  /transaksi:
    $ref: './paths/Transaksi/Transaksi.yaml'

  /transaksi/{idTransaksi}:
    $ref: './paths/Transaksi/Transaksi-{idTransaksi}.yaml'
